name: Windows

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Compile
      run: nodejs_bin\node.exe Kinc/make.js -v vs2019 --compile
    - name: Get Krom_bin
      run: git clone https://github.com/Kode/Krom_bin.git
    - name: Copy binary
      run: copy build\x64\Release\Krom.exe Krom_bin\Krom.exe
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      run: git -C Krom_bin commit -a -m "Update Windows binary to ${env:GITHUB_SHA}."
    - name: Push binary
      run: git -C Krom_bin push https://Kode-Robbot:${env:ROBBOT_PASS}@github.com/Kode/Krom_bin.git master --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
