name: Windows

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'
    - name: Get DLC
      run: .\get_dlc.bat
    - name: Create Kinc build files
      run: py kinc_gyp.py
    - name: Compile
      run: .\vcbuild.bat openssl-no-asm
